//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adm_Cfg_Workflow
    {
        public Adm_Cfg_Workflow()
        {
            this.Adm_Cfg_WorkflowLine = new HashSet<Adm_Cfg_WorkflowLine>();
        }
    
        public int ApprId { get; set; }
        public string PropertyID { get; set; }
        public string ApprovalDoc { get; set; }
        public string DescriptionE { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public string Executive { get; set; }
        public bool IsActive { get; set; }
        public byte[] WzTimeStamp { get; set; }
        public string InsertUser { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string InsertPCName { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatePCName { get; set; }
    
        public virtual ICollection<Adm_Cfg_WorkflowLine> Adm_Cfg_WorkflowLine { get; set; }
    }
}
