//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adm_Cfg_CodeType
    {
        public int Code_Id { get; set; }
        public string CodeType { get; set; }
        public string DescriptionE { get; set; }
        public string Description { get; set; }
        public string CustomField1Label1 { get; set; }
        public string CustomField1Label2 { get; set; }
        public string CustomField1Label3 { get; set; }
        public string CustomField1Label4 { get; set; }
        public string CustomField1Label5 { get; set; }
        public bool IsSystem { get; set; }
        public bool IsActive { get; set; }
        public string InsertUser { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertPCName { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatePCName { get; set; }
        public byte[] wzTimeStamp { get; set; }
    }
}
