//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adm_Cfg_AppParameter
    {
        public int ParameterId { get; set; }
        public string PropertyID { get; set; }
        public string ParameterName { get; set; }
        public string ParameterValue { get; set; }
        public string Description { get; set; }
        public string ParameterGroup { get; set; }
        public string ParameterType { get; set; }
        public string ParameterDisplay { get; set; }
        public string LOV_Values { get; set; }
        public string Explanation { get; set; }
        public Nullable<bool> DisplayYN { get; set; }
        public string UsedInApp { get; set; }
        public Nullable<bool> CanDeleteYN { get; set; }
        public Nullable<bool> StoredInCompany { get; set; }
        public Nullable<int> SequenceID { get; set; }
        public byte[] wzTimeStamp { get; set; }
        public string InsertUser { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertPCName { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatePCName { get; set; }
    }
}
