//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adm_Cfg_WorkflowLine
    {
        public int ApprDetailId { get; set; }
        public int ApprId { get; set; }
        public string ApprType { get; set; }
        public int Rank { get; set; }
        public string EmailID { get; set; }
        public byte[] WzTimeStamp { get; set; }
    
        public virtual Adm_Cfg_Workflow Adm_Cfg_Workflow { get; set; }
    }
}
