//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_Employee
    {
        public INT_Employee()
        {
            this.INT_ActiveLeave = new HashSet<INT_ActiveLeave>();
        }
    
        public string Level1 { get; set; }
        public string EmployeeID { get; set; }
        public string Level2 { get; set; }
        public string Level3 { get; set; }
        public string Level4 { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public string TaskCodeID { get; set; }
        public string Description { get; set; }
        public string DescriptionE { get; set; }
        public string JobTitle { get; set; }
        public string JobDesc { get; set; }
        public Nullable<bool> IsExecutive { get; set; }
        public Nullable<bool> MultiAccess { get; set; }
        public Nullable<bool> Posted { get; set; }
        public Nullable<bool> OTApply { get; set; }
        public Nullable<bool> AddToAttendance { get; set; }
        public Nullable<bool> IsSystemUser { get; set; }
        public byte[] wzTimeStamp { get; set; }
        public string InsertUser { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertPCName { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatePCName { get; set; }
    
        public virtual ICollection<INT_ActiveLeave> INT_ActiveLeave { get; set; }
        public virtual INT_JobTitle INT_JobTitle { get; set; }
        public virtual INT_Level1 INT_Level1 { get; set; }
        public virtual INT_Level2 INT_Level2 { get; set; }
        public virtual INT_Level3 INT_Level3 { get; set; }
        public virtual INT_Level4 INT_Level4 { get; set; }
        public virtual INT_TaskCode INT_TaskCode { get; set; }
    }
}
