//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_JobTitle
    {
        public INT_JobTitle()
        {
            this.INT_Employee = new HashSet<INT_Employee>();
        }
    
        public int JobTitleID { get; set; }
        public string Code { get; set; }
        public string JobBand { get; set; }
        public string Description { get; set; }
        public string DescriptionE { get; set; }
        public byte[] WzTimeStamp { get; set; }
        public string InsertUser { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertPCName { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatePCName { get; set; }
    
        public virtual ICollection<INT_Employee> INT_Employee { get; set; }
    }
}
