//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ReportStyle
    {
        public int ReportStyleID { get; set; }
        public Nullable<int> ReportID { get; set; }
        public string RptName { get; set; }
        public string QueryName { get; set; }
        public string Description { get; set; }
        public string DescriptionA { get; set; }
        public Nullable<int> ReportGroupID { get; set; }
        public Nullable<bool> ReportView { get; set; }
        public Nullable<int> Copies { get; set; }
        public string Orientation { get; set; }
        public Nullable<bool> AutoPrint { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Procedures { get; set; }
        public string ReportDatabase { get; set; }
        public string SubRptsAndQrys { get; set; }
        public string PrtOptOutputDevice { get; set; }
        public byte[] wzTimeStamp { get; set; }
    }
}
