//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Log_Sessions
    {
        public int SerialNo { get; set; }
        public string Location { get; set; }
        public string PCName { get; set; }
        public string UserId { get; set; }
        public System.DateTime LoginDate { get; set; }
        public Nullable<System.TimeSpan> LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutDate { get; set; }
        public Nullable<System.TimeSpan> LogoutTime { get; set; }
        public string Module { get; set; }
        public byte[] wzTimeStamp { get; set; }
    }
}
