//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Sec_Permissions
    {
        public Sys_Sec_Permissions()
        {
            this.Sys_Sec_PermissionsGranted = new HashSet<Sys_Sec_PermissionsGranted>();
        }
    
        public int PId { get; set; }
        public Nullable<int> FormID { get; set; }
        public string Permission { get; set; }
        public string PType { get; set; }
        public string Module { get; set; }
        public string PermissionGroup { get; set; }
        public string Description { get; set; }
        public string DescriptionArabic { get; set; }
        public string PermissionDisplay { get; set; }
        public Nullable<int> SequenceID { get; set; }
        public string TrusteePermissionYN { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string InsertUser { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertPCName { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatePCName { get; set; }
        public byte[] wzTimeStamp { get; set; }
    
        public virtual ICollection<Sys_Sec_PermissionsGranted> Sys_Sec_PermissionsGranted { get; set; }
    }
}
