//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Log_All
    {
        public int ID { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<byte> Period { get; set; }
        public Nullable<byte> Day { get; set; }
        public string UserID { get; set; }
        public string PCName { get; set; }
        public string TrxType { get; set; }
        public Nullable<System.DateTime> TrxDate { get; set; }
        public string TrxNo { get; set; }
        public string PropertyID { get; set; }
        public string SubSection { get; set; }
        public string EmployeeID { get; set; }
        public string Name { get; set; }
        public string Action { get; set; }
        public string Notes { get; set; }
        public System.DateTime LogDate { get; set; }
        public byte[] WzTimeStamp { get; set; }
    }
}
