//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Log_Error
    {
        public int SerialNo { get; set; }
        public string PCName { get; set; }
        public string UserID { get; set; }
        public string ErrorNo { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorDescription { get; set; }
        public string FormName { get; set; }
        public string ModuleName { get; set; }
        public string FunctionName { get; set; }
        public string LineNumber { get; set; }
        public string ErrType { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
