//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Report
    {
        public int ReportID { get; set; }
        public string ModuleCode { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Description_En { get; set; }
        public string Description_Ar { get; set; }
        public string ReportSystemName { get; set; }
        public string ReportSystemName_E { get; set; }
        public string ReportType { get; set; }
        public string RecordSource { get; set; }
        public string Procedures { get; set; }
        public string Criteria { get; set; }
        public string CriteriaSQL { get; set; }
        public string ReportTitle { get; set; }
        public Nullable<bool> Selected { get; set; }
        public Nullable<bool> Original { get; set; }
        public Nullable<bool> ShowReport { get; set; }
        public string VoucherType { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> SequenceID { get; set; }
        public byte[] wzTimeStamp { get; set; }
    }
}
