//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ReportCriteria
    {
        public int ReportCriteriaID { get; set; }
        public string Description_Ar { get; set; }
        public string Description_En { get; set; }
        public string DisplayControl { get; set; }
        public string DataType { get; set; }
        public string Operator { get; set; }
        public string TableName { get; set; }
        public string TextField { get; set; }
        public string ValueField { get; set; }
        public string DataSource { get; set; }
        public string Mask { get; set; }
        public string Format { get; set; }
        public string DefaultValue { get; set; }
        public string Remarks { get; set; }
        public string SQL_Parameter { get; set; }
        public string ParaHint { get; set; }
        public bool SortVisible { get; set; }
        public int SequenceID { get; set; }
        public byte[] wzTimeStamp { get; set; }
    }
}
