//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Sec_User
    {
        public Sys_Sec_User()
        {
            this.Sys_Sec_Access = new HashSet<Sys_Sec_Access>();
            this.Sys_Sec_PermissionsGranted = new HashSet<Sys_Sec_PermissionsGranted>();
            this.Sys_Sec_UserGroupings = new HashSet<Sys_Sec_UserGroupings>();
        }
    
        public int AppUserID { get; set; }
        public string PropertyID { get; set; }
        public string EmployeeID { get; set; }
        public string AppUser { get; set; }
        public string AppPassword { get; set; }
        public string ApproverType { get; set; }
        public string AppUserType { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string LastLoggedProperty { get; set; }
        public string LastLoggedLocation { get; set; }
        public Nullable<short> MaxUserSessions { get; set; }
        public Nullable<System.DateTime> PwdLastChanged { get; set; }
        public Nullable<short> PwdChangeDays { get; set; }
        public Nullable<short> GraceLogin { get; set; }
        public string ForcePwdChange { get; set; }
        public string AccountLockedOutYN { get; set; }
        public string PreventAccountLockout { get; set; }
        public Nullable<System.DateTime> LockoutDate { get; set; }
        public string InsertUser { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertPCName { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatePCName { get; set; }
        public byte[] wzTimeStamp { get; set; }
        public string DB_UID { get; set; }
        public string DB_Password { get; set; }
        public Nullable<System.DateTime> InActiveDate { get; set; }
        public string Title { get; set; }
        public string DefaultForm { get; set; }
        public string Name { get; set; }
        public string NameArabic { get; set; }
        public Nullable<int> DefaultCashierID { get; set; }
        public string AppUserDescription { get; set; }
        public Nullable<int> PersonNameID { get; set; }
        public Nullable<System.DateTime> DisabledUntil { get; set; }
        public Nullable<System.DateTime> DisabledOn { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
        public string DefaultLanguage { get; set; }
        public Nullable<System.DateTime> LastLoggedTimeStamp { get; set; }
        public Nullable<bool> IsSuperUser { get; set; }
        public string GeneralFilePath { get; set; }
        public string UserFilePath { get; set; }
        public string DefaultLocation { get; set; }
        public string InternalYN { get; set; }
        public string DefaultTerminal { get; set; }
        public string Sex { get; set; }
        public string InActiveReasonCode { get; set; }
        public Nullable<System.DateTime> InActiveFrom { get; set; }
        public Nullable<System.DateTime> InActiveTo { get; set; }
        public string Remarks { get; set; }
        public string EmpStatus { get; set; }
        public string AuthorizerYN { get; set; }
        public Nullable<System.DateTime> AuthorizerInActiveDate { get; set; }
        public string ReceiveBroadCastMsg { get; set; }
        public string MessageType { get; set; }
        public Nullable<short> CashierID { get; set; }
        public Nullable<bool> UseRemote { get; set; }
        public string Ribbon { get; set; }
        public Nullable<bool> ReportDesigner { get; set; }
    
        public virtual ICollection<Sys_Sec_Access> Sys_Sec_Access { get; set; }
        public virtual ICollection<Sys_Sec_PermissionsGranted> Sys_Sec_PermissionsGranted { get; set; }
        public virtual ICollection<Sys_Sec_UserGroupings> Sys_Sec_UserGroupings { get; set; }
    }
}
