//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_UI
    {
        public int uiID { get; set; }
        public string uiModuleCode { get; set; }
        public string uiPage { get; set; }
        public string uiGroup { get; set; }
        public string uiSubGroup { get; set; }
        public string uiName { get; set; }
        public string Description_En { get; set; }
        public string uiUrl { get; set; }
        public string uiImageUrl { get; set; }
        public int uiType { get; set; }
        public string uiUserControl { get; set; }
        public string Description_Ar { get; set; }
    }
}
