//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ReportCriteriaJoin
    {
        public int ReportCriteriaJoinID { get; set; }
        public Nullable<int> ReportStyleID { get; set; }
        public Nullable<int> ReportCriteriaID { get; set; }
        public int CriteriaType { get; set; }
        public string TableName { get; set; }
        public byte[] wzTimeStamp { get; set; }
        public string DefaultValue { get; set; }
    }
}
