//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Language
    {
        public int ID { get; set; }
        public string Description_En { get; set; }
        public string Description_Ar { get; set; }
        public string Culture { get; set; }
        public bool UseRtl { get; set; }
        public string DataDescriptionFieldName { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    }
}
