//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_SM_Shifts_Days
    {
        public int ShiftDayID { get; set; }
        public int ShiftID { get; set; }
        public byte DayID { get; set; }
        public byte DayStatus { get; set; }
        public System.TimeSpan Day1TimeIn { get; set; }
        public System.TimeSpan Day1TimeOut { get; set; }
        public Nullable<decimal> Day1WorkHours { get; set; }
        public System.TimeSpan Day2TimeIn { get; set; }
        public System.TimeSpan Day2TimeOut { get; set; }
        public Nullable<decimal> Day2WorkHours { get; set; }
        public decimal DayGracePeriodIn { get; set; }
        public decimal DayGracePeriodOut { get; set; }
        public decimal DayMaxTimeOut { get; set; }
        public decimal DayAbsenceAfterTimeIn { get; set; }
        public decimal DayExitPermission { get; set; }
        public bool DayGracePeriodActive { get; set; }
        public string DayNotes { get; set; }
        public string InsertUser { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertPCName { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatePCName { get; set; }
        public byte[] wzTimeStamp { get; set; }
    
        public virtual TA_SM_Cfg_WeekDays TA_SM_Cfg_WeekDays { get; set; }
        public virtual TA_SM_Shifts TA_SM_Shifts { get; set; }
    }
}
