//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_SM_Shifts_Employee_Mapping_Line
    {
        public int MapDtlID { get; set; }
        public int MapID { get; set; }
        public int ShiftID { get; set; }
        public byte TaDay { get; set; }
        public string Notes { get; set; }
        public string InsertUser { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertPCName { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatePCName { get; set; }
        public byte[] wzTimeStamp { get; set; }
    
        public virtual TA_SM_Shifts_Employee_Mapping TA_SM_Shifts_Employee_Mapping { get; set; }
    }
}
