//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_SM_PunchLog
    {
        public long PunchLogID { get; set; }
        public long PunchID { get; set; }
        public Nullable<byte> PunchInOut { get; set; }
        public byte PunchType { get; set; }
        public System.DateTime PunchDate { get; set; }
        public System.TimeSpan PunchTime { get; set; }
        public string EmployeeID { get; set; }
        public string PunchReaderNo { get; set; }
        public System.DateTime PunchProcessDate { get; set; }
    }
}
