//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_SM_Shifts_Employee_Mapping
    {
        public TA_SM_Shifts_Employee_Mapping()
        {
            this.TA_SM_Shifts_Employee_Mapping_Line = new HashSet<TA_SM_Shifts_Employee_Mapping_Line>();
        }
    
        public int MapID { get; set; }
        public string EmployeeID { get; set; }
        public int TA_Year { get; set; }
        public int TA_Month { get; set; }
        public string Shift_Day01 { get; set; }
        public string Shift_Day02 { get; set; }
        public string Shift_Day03 { get; set; }
        public string Shift_Day04 { get; set; }
        public string Shift_Day05 { get; set; }
        public string Shift_Day06 { get; set; }
        public string Shift_Day07 { get; set; }
        public string Shift_Day08 { get; set; }
        public string Shift_Day09 { get; set; }
        public string Shift_Day10 { get; set; }
        public string Shift_Day11 { get; set; }
        public string Shift_Day12 { get; set; }
        public string Shift_Day13 { get; set; }
        public string Shift_Day14 { get; set; }
        public string Shift_Day15 { get; set; }
        public string Shift_Day16 { get; set; }
        public string Shift_Day17 { get; set; }
        public string Shift_Day18 { get; set; }
        public string Shift_Day19 { get; set; }
        public string Shift_Day20 { get; set; }
        public string Shift_Day21 { get; set; }
        public string Shift_Day22 { get; set; }
        public string Shift_Day23 { get; set; }
        public string Shift_Day24 { get; set; }
        public string Shift_Day25 { get; set; }
        public string Shift_Day26 { get; set; }
        public string Shift_Day27 { get; set; }
        public string Shift_Day28 { get; set; }
        public string Shift_Day29 { get; set; }
        public string Shift_Day30 { get; set; }
        public string Shift_Day31 { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Notes { get; set; }
        public string InsertUser { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertPCName { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatePCName { get; set; }
        public byte[] wzTimeStamp { get; set; }
    
        public virtual ICollection<TA_SM_Shifts_Employee_Mapping_Line> TA_SM_Shifts_Employee_Mapping_Line { get; set; }
    }
}
