//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_SM_Shifts
    {
        public TA_SM_Shifts()
        {
            this.TA_SM_Shifts_Days = new HashSet<TA_SM_Shifts_Days>();
            this.TA_SM_Shifts_Dept_Mapping = new HashSet<TA_SM_Shifts_Dept_Mapping>();
        }
    
        public int ShiftID { get; set; }
        public string PropertyID { get; set; }
        public string ShiftUserCode { get; set; }
        public string Description_En { get; set; }
        public string Description_Ar { get; set; }
        public string ShiftDescE { get; set; }
        public string ShiftDesc { get; set; }
        public string ShiftShortDesc { get; set; }
        public System.TimeSpan Punch1StartTime { get; set; }
        public System.TimeSpan Punch1EndTime { get; set; }
        public System.TimeSpan Punch2StartTime { get; set; }
        public System.TimeSpan Punch2EndTime { get; set; }
        public bool ShiftRamadanActive { get; set; }
        public bool IsSplitShift { get; set; }
        public System.TimeSpan Punch1StartTime_Ramadan { get; set; }
        public System.TimeSpan Punch1EndTime_Ramadan { get; set; }
        public System.TimeSpan Punch2StartTime_Ramadan { get; set; }
        public System.TimeSpan Punch2EndTime_Ramadan { get; set; }
        public int TaTypeId { get; set; }
        public string Shifts_Notes { get; set; }
        public string ApprovedBY { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string InsertUser { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertPCName { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatePCName { get; set; }
        public byte[] wzTimeStamp { get; set; }
    
        public virtual ICollection<TA_SM_Shifts_Days> TA_SM_Shifts_Days { get; set; }
        public virtual ICollection<TA_SM_Shifts_Dept_Mapping> TA_SM_Shifts_Dept_Mapping { get; set; }
        public virtual TA_TS_Cfg_AttendanceTypes TA_TS_Cfg_AttendanceTypes { get; set; }
    }
}
