//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_SM_Cfg_WeekDays
    {
        public TA_SM_Cfg_WeekDays()
        {
            this.TA_SM_Shifts_Days_Ramadan = new HashSet<TA_SM_Shifts_Days_Ramadan>();
            this.TA_SM_Shifts_Days = new HashSet<TA_SM_Shifts_Days>();
        }
    
        public byte DayID { get; set; }
        public byte DayCode { get; set; }
        public string DayName { get; set; }
        public string DayNameE { get; set; }
        public string DayIndex { get; set; }
        public string Description_Ar { get; set; }
        public string Description_En { get; set; }
        public string InsertUser { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertPCName { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatePCName { get; set; }
        public byte[] wzTimeStamp { get; set; }
        public string DayShortNameA { get; set; }
        public string DayShortNameE { get; set; }
    
        public virtual ICollection<TA_SM_Shifts_Days_Ramadan> TA_SM_Shifts_Days_Ramadan { get; set; }
        public virtual ICollection<TA_SM_Shifts_Days> TA_SM_Shifts_Days { get; set; }
    }
}
