//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_SM_Ramadan
    {
        public TA_SM_Ramadan()
        {
            this.TA_SM_Shifts_Days_Ramadan = new HashSet<TA_SM_Shifts_Days_Ramadan>();
        }
    
        public int RamadanID { get; set; }
        public System.DateTime RamadanDateFrom { get; set; }
        public System.DateTime RamadanDateTo { get; set; }
        public Nullable<decimal> RamadanHours { get; set; }
        public string RamadanNotes { get; set; }
        public string ApprovedBY { get; set; }
        public string InsertUser { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertPCName { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatePCName { get; set; }
        public byte[] wzTimeStamp { get; set; }
    
        public virtual ICollection<TA_SM_Shifts_Days_Ramadan> TA_SM_Shifts_Days_Ramadan { get; set; }
    }
}
