//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_TS_Cfg_AttendanceTypes
    {
        public TA_TS_Cfg_AttendanceTypes()
        {
            this.TA_SM_Shifts = new HashSet<TA_SM_Shifts>();
            this.TA_TS_Cfg_AttendanceTypesMapping = new HashSet<TA_TS_Cfg_AttendanceTypesMapping>();
        }
    
        public int TaTypeId { get; set; }
        public string PropertyID { get; set; }
        public string TaUserCode { get; set; }
        public string Description_En { get; set; }
        public string Description_Ar { get; set; }
        public string TaCategory { get; set; }
        public string TaType { get; set; }
        public string TaMode { get; set; }
        public string TaHoursOperation { get; set; }
        public string TaPayOperation { get; set; }
        public decimal TaPayRate { get; set; }
        public bool TaIsNoPay { get; set; }
        public bool TaDeductFromVacBal { get; set; }
        public string TaDefaultHours { get; set; }
        public string TaAllowedUser { get; set; }
        public string SalaryCalc { get; set; }
        public Nullable<short> SequenceID { get; set; }
        public string ApprovedBY { get; set; }
        public bool Active { get; set; }
        public string InsertUser { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertPCName { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatePCName { get; set; }
        public byte[] wzTimeStamp { get; set; }
    
        public virtual ICollection<TA_SM_Shifts> TA_SM_Shifts { get; set; }
        public virtual ICollection<TA_TS_Cfg_AttendanceTypesMapping> TA_TS_Cfg_AttendanceTypesMapping { get; set; }
    }
}
