//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAdm_Cfg_Code_Sorting
    {
        public int CodeID { get; set; }
        public string CodeType { get; set; }
        public string UserCode { get; set; }
        public string Description_En { get; set; }
        public string Description_Ar { get; set; }
        public string CustomField1 { get; set; }
        public byte SequenceID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
