//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTA_TS_Cfg_AttendanceDays
    {
        public int AttendanceID { get; set; }
        public string PropertyID { get; set; }
        public Nullable<int> TaMonth { get; set; }
        public Nullable<byte> C1 { get; set; }
        public Nullable<byte> C2 { get; set; }
        public Nullable<byte> C3 { get; set; }
        public Nullable<byte> C4 { get; set; }
        public Nullable<byte> C5 { get; set; }
        public Nullable<byte> C6 { get; set; }
        public Nullable<byte> C7 { get; set; }
        public Nullable<byte> C8 { get; set; }
        public Nullable<byte> C9 { get; set; }
        public Nullable<byte> C10 { get; set; }
        public Nullable<byte> C11 { get; set; }
        public Nullable<byte> C12 { get; set; }
        public Nullable<byte> C13 { get; set; }
        public Nullable<byte> C14 { get; set; }
        public Nullable<byte> C15 { get; set; }
        public Nullable<byte> C16 { get; set; }
        public Nullable<byte> C17 { get; set; }
        public Nullable<byte> C18 { get; set; }
        public Nullable<byte> C19 { get; set; }
        public Nullable<byte> C20 { get; set; }
        public Nullable<byte> C21 { get; set; }
        public Nullable<byte> C22 { get; set; }
        public Nullable<byte> C23 { get; set; }
        public Nullable<byte> C24 { get; set; }
        public Nullable<byte> C25 { get; set; }
        public Nullable<byte> C26 { get; set; }
        public Nullable<byte> C27 { get; set; }
        public Nullable<byte> C28 { get; set; }
        public Nullable<byte> C29 { get; set; }
        public Nullable<byte> C30 { get; set; }
        public Nullable<byte> C31 { get; set; }
        public string Notes { get; set; }
        public string InsertUser { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertPCName { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatePCName { get; set; }
    }
}
